services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data/docker:/usr/share/docker
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
